### ISSUE TITLE
Unknown URL Format errors

### ISSUE THREAD

**Issue by danizen** [Valassis-Digital-Media/nbconflux#13]
I was extremely excited to hear about nbconflux at the Jupyter DC Pop-up, and even though it isn't entirely working right with our authentication, which is not username password, I can at least give this much feedback.

* When I use an URL from my personal space, it doesn't resolve the page id:

```nbconflux notebooks/MissingTitle.ipynb 'https://this.is.not.real.gov/confluence/display/~davisda4/Test+Notebook```

* When I use an URL from a data science space, it doesn't resolve the page id:

```nbconflux notebooks/MissingTitle.ipynb 'https://this.is.not.real.gov/confluence/display/WSO/Jupyter+Notebook+Page+-+Missing+Titles'```

* It only works if I edit the page, and copy the URL containing the pageid.  So, you are relying a lot on the configuration of Confluence, which is fine starting out.

More soon, after I figure out how to step it through our authentication.

**Comment by parente** [comment]
@danizen Glad to have you as a first user reporting issues against a Confluence instance! That's the only way the code here is going to get smarter, since I have just 2 very-specifically-configured instances to test against.

> even though it isn't entirely working right with our authentication, which is not username password, I can at least give this much feedback.

Happy to take a PR if making it work with other auth mechanisms doesn't require tremendous code changes. If it does, we should probably focus on making the auth mechanism an extension point so that the core code here remains simple, but allows you and others to plug-in your own auth support elsewhere.

> When I use an URL from my personal space, it doesn't resolve the page id:

There's a set of rules in the code base for how to resolve these URLs to a page ID. Interestingly enough, in our Server instance, it resolves my personal space without issue. In our cloud instance, I don't have one so can't test. Happy to take a PR if you can figure out what rule needs to be added / extended.

> When I use an URL from a data science space, it doesn't resolve the page id:

Interesting. This is bread and butter in our use of Confluence Server: our teams post to their own spaces all the time. I don't see anything different about your URL structure here than ours / what the code should be supporting.

> It only works if I edit the page, and copy the URL containing the pageid. So, you are relying a lot on the configuration of Confluence, which is fine starting out.

Indeed. See top of comment. 😉

**Comment by danizen** [comment]
Please close; I was able to get this done after our internal Confluence administrators updated Confluence.
See [pull request 21](https://github.com/Valassis-Digital-Media/nbconflux/pull/21) for some changes I needed to make it work with CPython 3.5.1 rather than whatever Anaconda you guys are running.

**Comment by markheckmann** [comment]
@danizen I get the same error message. Do you have any info on what version caused the problem? Or alternatively: Do you know which confluence version you are using currently? Thanks!
